<a href="https://colab.research.google.com/github/soyeunju/ESAA/blob/main/ESAA_0905_1%EC%A3%BC%EC%B0%A8_%EA%B3%BC%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1-3. 넘파이
###개념:
- Numerical Python을 의미하는 넘파이 (NumPy)는 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지.
- 대량 데이터의 배열 연산을 가능하게 하므로 빠른 배열 연산 속도를 보장
- 배열 기반의 연산, 다양한 데이터 핸들링 가능

## 넘파이 ndarray

In [1]:
import numpy as np

- .array(): 리스트와 같은 다양한 인자를 입력받아서 ndarray로 변환하는 기능

- .shape(): ndarray의 차원과 크기를 튜플(tuple)
- .ndim(): array의 차원
- .dtype(): 데이터 속성
- .astype(): ndarray 내 데이터값의 타입 변경. 메모리 절약을 위해 활용
- .arange(): 연속값. 0부터 인자 값 -1까지. start, stop 인자로 줄 수 있음
- .ones(): 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 0으로 채운 ndarray를 반환
- .zeros():함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 1으로 채운 ndarray를 반환
- .reshape():ndarray를 특정 차원 및 크기로 변환

In [2]:
#.array()
#.shape()
array1 = np.array([1,2,3])
print('array1 type:',type(array1))
print('array1 array 형태',array1.shape)


array2 = np.array([[1,2,3],
                   [4,5,6]])
print('array2 type:',type(array2))
print('array2 array 형태',array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:',type(array3))
print('array3 array 형태',array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태 (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태 (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태 (1, 3)


In [3]:
#.ndim()
print('array1:{0}차원, array2:{1}차원, array3:{2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

array1:1차원, array2:2차원, array3:2차원


In [4]:
#.dtype()
list1=[1,2,3]
print(type(list1))
array1=np.array(list1)
print(type(array1))
print(array1,array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [5]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2,array2.dtype)

list3=[1,2,3.0]
array3=np.array(list3)
print(array3,array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [7]:
#.astype()
array_int=np.array([1,2,3])
array_float=array_int.astype('float64')
print(array_float,array_float.dtype)

array_int1=array_float.astype('int32')
print(array_int1,array_int1.dtype)

[1. 2. 3.] float64
[1 2 3] int32


In [8]:
#.arange()
sequence_array=np.arange(10)
print(sequence_array)
print(sequence_array.dtype,sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [9]:
#.zeros()
#.ones()
zero_array=np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array=np.ones((3,2),dtype='int32')
print(one_array)
print(one_array.dtype,one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1 1]
 [1 1]
 [1 1]]
int32 (3, 2)


In [13]:
#.reshape()
array1=np.arange(10)
print('array1:\n',array1)

array2=array1.reshape(2,5)
print('array2:\n',array2)

array3=array1.reshape(5,2)
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [14]:
array1.reshape(4,3) # 지정된 사이즈로 변경이 불가능하면 오류를 발생

ValueError: cannot reshape array of size 10 into shape (4,3)

In [15]:
#.reshape()
array1=np.arange(10)
print(array1)

array2=array1.reshape(-1,5) # -1을 인자로 사용하면 원래 ndarray와 호환되는 새로운 shape로 변환
print('array2 shape:',array2.shape)

array3=array1.reshape(5,-1) # -1을 인자로 사용하면 원래 ndarray와 호환되는 새로운 shape로 변환
print('array3 shape:',array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [16]:
array1 = np.arange(10)
array4 = array1.reshape(-1, 4) # 물론 -1을 사용하더라도 호환 될 수 없는 형태는 변환할 수 없음

ValueError: cannot reshape array of size 10 into shape (4)

In [19]:
#.reshape()
array1=np.arange(8)
array3d=array1.reshape((2,2,2))
print('array3d:\n',array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5=array3d.reshape(-1,1) # -1 인자는 reshape(—1,1)와 같은 형태로 자주 사용됨. reshape(—1,1)은 원본 ndarray가 어떤 형태라도 2차원으로 변환
print('array5:\n',array5.tolist())
print('array5:\n',array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6=array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6:\n',array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5:
 (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6:
 (8, 1)


##인덱싱(Indexing)
###개념:
- 특정한 데이터만 추출: 원하는 위치의 인덱스 값을 지정하면 해당 위치의 데이터가 반환
- 슬라이싱: 연속된 인덱스상의 ndarray를 추출하는 방식. " : " 기호 활용
- 팬시 인덱싱(Fancy Indexing): 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정
- 불린 인덱싱(Boolean Indexing): 특정 조건에 해당하는지 여부인 True/False 값 인덱싱 집합을 기반으로 True 에 해당하는 인덱스 위치에 있는 데이터의 ndarray 반환

### 단일 값 추출

In [20]:

# 1부터 9까지의 1차원 ndarray 생성
array1=np.arange(start=1,stop=10)
print('array1:',array1)

value=array1[2]
print('value:',value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [21]:
print('맨 뒤의 값:',array1[-1],'맨 뒤에서 두 번째 값:',array1[-2]) # 인덱스 -1은 맨 뒤 의 데이터값을 의미

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


In [22]:
# 단일 인덱스를 이용해 ndarray 내의 데이터값도 간단히 수정 가능
array1[0]=9
array1[8]=0
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 0]


In [26]:
# 다차원 ndarray에서 단일 값을 추출
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:',array2d[0,0])
print('(row=0, col=1) index 가리키는 값:',array2d[0,1])
print('(row=1, col=0) index 가리키는 값:',array2d[1,0])
print('(row=2, col=2) index 가리키는 값:',array2d[2,2])

# axis 0은 로우 방향의 축을 의미, axis 1은 칼럼 방향의 축을 의미. 3차원은 여기에 axis 2 추가.
# [row=0, col=1] 인덱싱은 [axis 0=0, axis 1=1]이 정확한 표현

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


###슬라이싱

In [28]:
array1=np.arange(start=1,stop=10)
array3= array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [31]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3] # : 앞에 아무 것도 적지 않으면 0으로 간주
print(array4)
array5 = array1[3:] # : 뒤에 아무 것도 적지 않으면 맨 마지막 인덱스로 간주
print(array5)
array6 = array1[:] # : : 앞/뒤로 아무 것도 적지 않으면 자동으로 맨 처음/ 맨 마지막 인덱스로 간주
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [33]:
# 2차원 ndarray에서 슬라이싱
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)
print('array2d:\n',array2d)

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [40]:
print('array2d[0:2,0:2]:\n',array2d[0:2,0:2])
print('array2d[1:3,0:3]:\n',array2d[1:3,0:3])
print('array2d[1:3,:]:\n',array2d[1:3,:]) # : 앞/뒤로 아무 것도 적지 않으면 전체로 간주
print('array2d[:,:]:\n',array2d[:,:])
print('array2d[:2,1:]:\n',array2d[:2,1:])
print('array2d[:2,0]:\n',array2d[:2,0]) # 단일 값 추출

array2d[0:2,0:2]:
 [[1 2]
 [4 5]]
array2d[1:3,0:3]:
 [[4 5 6]
 [7 8 9]]
array2d[1:3,:]:
 [[4 5 6]
 [7 8 9]]
array2d[:,:]:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2,1:]:
 [[2 3]
 [5 6]]
array2d[:2,0]:
 [1 4]


In [41]:
# 2차원 ndarray에서 뒤에 오는 인덱스를 없애면 1차원 ndarray를 반환
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:',array2d[0].shape,'array2d[1] shape:,',array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape:, (3,)


###팬시 인덱싱(Fancy Indexing)
#### 개념:
- 리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식

In [49]:
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)

array3=array2d[[0,1],2]
print('array2d[[0,1], 2] => ', array3.tolist())

array4=array2d[[0,1],0:2]
print('array2d[[0,1],0:2] => ', array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] => ' ,array5.tolist())

array2d[[0,1], 2] =>  [3, 6]
array2d[[0,1],0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


###불린 인덱싱(Boolean indexing)
#### 개념:
- 조건 필터링과 검색을 동시에 할 수 있기 때문에 매우 자주 사용되 는 인덱싱 방식

- Step 1: array1d 〉 5와 같이 ndarray의 필터링 조건을 [ ] 안에 기재

- Step 2: False 값은 무시하고 True 값에 해당하는 인덱스값만 저장(유의해야 할 사항은 True값 자체인 1을 저장하는 것이 아니라 True값을 가진 인덱스를 저장한다는 것)

- Step 3: 저장된 인덱스 데이터 세트로 ndarray 조회


In [51]:
array1d=np.arange(start=1,stop=10)
# [ ] 안에 array1d > 5 Boolean indexing을 적용
array3=array1d[array1d>5]
print('array1d>5 불린 인덱싱 결과 값:',array3)
array1d > 5

array1d>5 불린 인덱싱 결과 값: [6 7 8 9]


array([False, False, False, False, False,  True,  True,  True,  True])

In [52]:
boolean_indexes=np.array([False,False,False,False,False,True,True,True,True])
array3=array1d[boolean_indexes]
print('불린 인덱스로 필터링 한 결과:',array3)

불린 인덱스로 필터링 한 결과: [6 7 8 9]


In [53]:
indexes=np.array([5,6,7,8])
array4=array1d[indexes]
print('일반 인덱스로 필터링 한 결과:',array4)

일반 인덱스로 필터링 한 결과: [6 7 8 9]


##행렬의 정렬

### 개념:
- .sort(): 넘파이에서 sort()를 호출하는 방식. 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬을 반환
- ndarray.sort(): 행렬 자체에서 sort()를 호출하는 방식. 원 행렬 자체를 정렬한 형태로 변환하며 반환 값은 None
- ndarray.sort()
- .argsort(): 정렬된 행렬의 원본 행렬 인덱스 반환

- 내림차순은 [::-1]을 적용

In [60]:
#np.sort(),ndarray.sort()
org_array=np.array([3,1,9,5])
print('원본 행렬:',org_array)

# np.sort()로 정렬
sort_array1=np.sort(org_array)
print('np.sort( ) 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort( ) 호출 후 원본 행렬:', org_array)

# ndarray.sort( )로 정렬
sort_array2=org_array.sort()
print('org_array.sort( ) 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort( ) 호출 후 원본 행렬:', org_array)

# 내림차순으로 정렬하는 방법: [::-1]을 적용. np.sort( )[::-1]과 같이 사용
sort_array_desc=np.sort(org_array)[::-1]
print('내림차순으로 정렬:',sort_array_desc)

원본 행렬: [3 1 9 5]
np.sort( ) 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort( ) 호출 후 원본 행렬: [3 1 9 5]
org_array.sort( ) 호출 후 반환된 행렬: None
org_array.sort( ) 호출 후 원본 행렬: [1 3 5 9]
내림차순으로 정렬: [9 5 3 1]


In [64]:
# 행렬이 2차원 이상일 경우에 axis 축 값 설정을 통해 로우 방향, 또는 칼럼 방향으로 정렬을 수행
array2d=np.array([[8,12],
                  [7,1]])
sort_array2d_axis0=np.sort(array2d,axis=0)
print('로우 방향으로 정렬:\n',sort_array2d_axis0)

sort_array2d_axis1=np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [67]:
#.argsort()
org_sort=np.array([3,1,9,5])
sort_indices=np.argsort(org_sort)
print(type(sort_indicies))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

org_array = np.array([3,1,9,5])
sort_indices_desc=np.argsort(org_array)[::-1] # 내림차순은 [::-1]으로 표시함.
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]
행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [69]:
import numpy as np

name_array= np.array(['John','Mike','Sarah','Kate','Sammuel'])
score_array=np.array([78,95,84,98,88])

sort_indices_asc=np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:',sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:',name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Sammuel' 'Mike' 'Kate']


##선형대수 연산

####행렬 내적(행렬 곱)
-.dot(A,B)

####전치 행렬
-.transpose(A)


In [73]:
#.dot()
A=np.array([[1,2,3],
            [4,5,6]])
B=np.array([[7,8],
            [9,10],
            [11,12]])
dot_product=np.dot(A,B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [74]:
#.transpose()
A=np.array([[1,2],
           [3,4]])
transpose_mat=np.transpose(A)
print('A의 전치 행렬:\n',transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
