<a href="https://colab.research.google.com/github/soyeunju/ESAA/blob/main/ESAA_0906_Week1_Session_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
import numpy as np

A = np.random.random((5,3))
B = np.random.random((3,2))

print(A)
print(B)
print(np.dot)

[[0.55196628 0.66869825 0.51169584]
 [0.2040713  0.44429743 0.95213335]
 [0.40023906 0.01173063 0.68797146]
 [0.99285506 0.20839207 0.43033169]
 [0.52079204 0.56017909 0.69786388]]
[[0.69749902 0.11875924]
 [0.6819713  0.7133351 ]
 [0.00976742 0.91593456]]
[[0.8460269  1.01123693]
 [0.45463752 1.21326015]
 [0.29388601 0.68603679]
 [0.83883607 0.66071976]
 [0.75209433 1.10064192]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
import numpy as np

A=np.arange(10)
A[(A>3)&(A<8)] *=-1
print(A)

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

9 ( -1+0+1+2+3+4)
10 (0+1+2+3+4)

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

1,2,4,5 -> 합법적
3,6 -> 비합법적(R)


#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

array(nan)
error
value error

In [71]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-71-cd809174da5d>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-71-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
<ipython-input-71-cd809174da5d>:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [72]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(Z1)
print(Z2)
print(np.unique(Z1[np.isin(Z1,Z2)]))

[6 3 0 6 8 6 5 0 2 3]
[5 6 2 9 3 6 4 5 5 1]
[2 3 5 6]


In [9]:
import numpy as np

Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)

common_value = np.intersect1d(Z1, Z2)

print("Z1:", Z1)
print("Z2:", Z2)
print(common_value)

Z1: [0 1 9 1 8 7 6 8 2 6]
Z2: [9 1 5 2 3 4 4 6 8 3]
[1 2 6 8 9]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

False. nan!=1j


In [14]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-14-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [20]:
Z = np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [29]:
A=np.random.randint(10)
B=np.random.randint(10)
C=np.add(A,B)
D=np.negative(A)
E=np.divide(D,2)
F=np.multiply(A,E)
print(F)

-2.0


#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [78]:
# 1.
np.random.seed(42)
A=np.random.uniform(0,10,5)
print(A//1)

# 2.
np.random.seed(42)
A=np.random.uniform(0,10,5)
print(A-A%1)

[3. 9. 7. 5. 1.]
[3. 9. 7. 5. 1.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [35]:
A=np.random.randint(0,5,25).reshape((5,5))
print(A)

[[1 1 3 3 1]
 [4 3 2 1 4]
 [3 4 1 1 2]
 [4 1 2 2 1]
 [1 1 2 1 3]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [45]:
A=np.random.randint(0,10,10)
print(A)
print(np.sort(A))

[0 6 9 0 9 0 1 4 7 9]
[0 0 0 1 4 6 7 9 9 9]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [46]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

print(np.array_equal(A,B))

False


#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [80]:
z = np.random.random((10, 2))
x, y = z[:, 0], z[:, 1]
r = np.sqrt(x**2 + y**2)
t = np.arctan2(y, x)
print(r)
print(t)

[0.81016721 0.7844693  0.60931797 0.18251078 1.35382015 0.86388415
 0.69116907 0.45675765 0.49636956 0.94542619]
[0.24902584 0.85592681 1.49448884 0.36443989 0.79414505 0.36035827
 1.42900735 0.27046938 0.06933562 0.27725634]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [53]:
Z=np.random.randint(0,10,10)
Z[Z.argmax()]=0
print(Z)

[5 8 5 8 5 5 0 7 0 9]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [81]:
Z = np.arange(100)
v = np.random.uniform(0,100)
distance=np.abs(Z-v)

closest_index=np.argmin(distance)
Z[closest_index]

66

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [84]:
import numpy as np

Z = np.arange(9).reshape(3,3)

for index in np.ndindex(Z.shape):
    print(f"Index: {index}, Value: {Z[index]}")

Index: (0, 0), Value: 0
Index: (0, 1), Value: 1
Index: (0, 2), Value: 2
Index: (1, 0), Value: 3
Index: (1, 1), Value: 4
Index: (1, 2), Value: 5
Index: (2, 0), Value: 6
Index: (2, 1), Value: 7
Index: (2, 2), Value: 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [63]:
n = 3
p = 2
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),8)
print(Z)

[[0. 0. 8.]
 [0. 0. 0.]
 [0. 0. 8.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [67]:
# column 1
Z = np.random.randint(0,10,(3,3))
print(Z)
Z[np.argsort(Z[:,0])]

[[7 5 7]
 [6 2 6]
 [7 3 1]]


array([[6, 2, 6],
       [7, 5, 7],
       [7, 3, 1]])

In [68]:
# column 2
Z = np.random.randint(0,10,(3,3))
print(Z)
Z[np.argsort(Z[:,1])]

[[4 1 1]
 [8 7 8]
 [8 4 8]]


array([[4, 1, 1],
       [8, 4, 8],
       [8, 7, 8]])

In [69]:
# column 3
Z = np.random.randint(0,10,(3,3))
print(Z)
Z[np.argsort(Z[:,2])]

[[8 5 6]
 [3 7 1]
 [8 7 9]]


array([[3, 7, 1],
       [8, 5, 6],
       [8, 7, 9]])